[project]
name = "jas-soiree-tech"
version = "0.2.0"
description = "School."
authors = [
    {name = "Łukasz Wieczorek",email = "luke@soiree.tech"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.16"
dependencies = []

[tool.poetry]
packages = [{include = "jas"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
